apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app-label
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: app
          image: dienigma/hor_app
          ports:
            - name: frontend
              containerPort: 3000
            - name: backend
              containerPort: 5000
