apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  ports:
    - name: client
      port: 80
      targetPort: 3000
    - name: server
      port: 81
      targetPort: 5000
  selector:
    app: app-label
  type: LoadBalancer
